version: "2"
services:
  web:
    image: akrn/webhook-ninja:latest
    volumes:
      - ./app-frontend-static:/var/www/html
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DBNAME: webhook-ninja
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
